apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: user1-eventsource
spec:
  service:
    ports:
      - port: 16917
        targetPort: 16917
        nodePort: 0
  webhook:
    upload:
      port: "16917"
      endpoint: /upload
      method: POST
    A:
      port: "16917"
      endpoint: /A
      method: POST
    entered:
      port: "16917"
      endpoint: /entered
      method: POST