apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: user1-eventsource
spec:
  service:
    ports:
      - port: "13665"
        targetPort: "13665"
        nodePort: 0
  webhook:
    upload:
      port: 13665
      endpoint: /upload
      method: POST
    A:
      port: 13665
      endpoint: /A
      method: POST
    entered:
      port: 13665
      endpoint: /entered
      method: POST